# permissions for end users to edit kdaemons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdaemon-editor-role
rules:
- apiGroups:
  - apps.kibazen.cn
  resources:
  - kdaemons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kibazen.cn
  resources:
  - kdaemons/status
  verbs:
  - get
