# permissions for end users to view kdaemons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdaemon-viewer-role
rules:
- apiGroups:
  - apps.kibazen.cn
  resources:
  - kdaemons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kibazen.cn
  resources:
  - kdaemons/status
  verbs:
  - get
