
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.kibazen.cn
  resources:
  - kdaemons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kibazen.cn
  resources:
  - kdaemons/finalizers
  verbs:
  - update
- apiGroups:
  - apps.kibazen.cn
  resources:
  - kdaemons/status
  verbs:
  - get
  - patch
  - update
